inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  Include:
    - 'lib/**/*'
    - 'test/**/*'
  Exclude:
    # pmdtester.gemspec and Gemfile are generated
    - 'pmdtester.gemspec'
    - 'Gemfile'
    - 'target/**/*'
    - 'test/resources/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'lib/pmdtester/parsers/options.rb'

Metrics/ClassLength:
  Exclude:
    - '**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/pmdtester/parsers/options.rb'
