language: ruby
before_install:
- LOCAL_DIR=${HOME}/.cache/openjdk
- TARGET_DIR=${HOME}/openjdk11
- mkdir -p ${LOCAL_DIR}
- mkdir -p ${TARGET_DIR}
- DOWNLOAD_URL="https://pmd-code.org/openjdk/latest/jdk-11/linux64.tar.gz"
- OPENJDK_ARCHIVE=$(basename $DOWNLOAD_URL)
- if [ ! -e ${LOCAL_DIR}/${OPENJDK_ARCHIVE} ]; then wget --directory-prefix ${LOCAL_DIR} --timestamping --continue ${DOWNLOAD_URL}; fi
- tar --extract --file ${LOCAL_DIR}/${OPENJDK_ARCHIVE} -C ${TARGET_DIR} --strip-components=1
- export JAVA_HOME="${TARGET_DIR}"
- export PATH="${TARGET_DIR}/bin:${PATH}"
- java -version
script:
- rake check_manifest
- rake rubocop
- rake clean test
- rake clean integration-test
- rake install_gem
- pmdtester -h

before_deploy:
- git stash --all
- rake hoe:spec

deploy:
  provider: rubygems
  api_key:
    secure: "PMohVxVpupi3qKmSWjny6ASPKiWpyZxMTluARs15tiRR4Pco3Ko+Z+Nk2F6XNZkY4q4zudS91JGtYeGzuBknI/tFB9S1LjR5RDe9cUbETlhpazBCaRvVFt0K8okb9JAWfVi+mnCG5saBn0Osxv/PKS2sVr/3dK9JFVncaYfRhIZfhB/LcdHMLpnlv94sr60SGPA8ITz3pj1dKe6E2wfqQjgD8RNOOLxtcTFeEZVHDuJn0gsKz+ou2Dyzth+2SksKKboosodWXNbAIx5xg+iVLZgGFluQknZ130G0PA6vJzMLWgLEjUtFDV1QtE80jP7LhuMOKXaXHa6NghHL7h3TiBO9/2SEdHSdIq5NeMm2f8qttLNqI15cgGolyUGd+K43tAdvNuJws+wbQsj53htGFLvSKPfwTxipn1Ppa1s6/bSeUQvtj/kXO6MnVdwTBNjlm791DaG8sC4WbvppLvrKPfpvqGoOfWj9h5PlB8SsaHyDtOB6oCYE354RxLJxaI6b4hcxleyz7mPmoPcKQjcPSM8i004lCCNAmPm0VMW/yTi1Z1iBq6+1OiW7fe6txJi9zCPhMzziz1EA0oQYBgu99Uy9wjHh8CkWXtZDx+WSYRxCZOJ6kFN72dgYQbIsn4kxzrjwCp+NN0woDPR0FXcuePNgAz2hBtAvbKdOC2OCQVw="
  on:
    tags: true
  skip_cleanup: true
  gem: pmdtester
  gemspec: pmdtester.gemspec

cache:
  directories:
  - vendor/bundle
  - "$HOME/.rvm/"
  - "$HOME/.cache/openjdk"
