name: Build

on:
  workflow_call:

# if another commit is added to the same branch or PR (same github.ref),
# then cancel already running jobs and start a new build.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  LANG: 'en_US.UTF-8'

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #v4.7.1
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Prepare HOME/openjdk11
        run: ln -sfn "${JAVA_HOME_11_X64}" "${HOME}/openjdk11"
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 #v4.2.4
        with:
          path: |
            ~/.m2/repository
            ~/.cache
            ~/.gradle
            vendor/bundle
            target/repositories
          key: v4-${{ runner.os }}-${{ hashFiles('pmdtester.gemspec') }}
          restore-keys: |
            v4-${{ runner.os }}-
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 #v1.254.0
        with:
          ruby-version: 3.3
      - name: Install dependencies (bundler)
        run: |
          # bundler should already be installed
          bundle --version
          bundle config set --local path vendor/bundle
          bundle install
      - name: Build with rake
        run: |
          bundle exec rake check_manifest
          bundle exec rake rubocop
          bundle exec rake clean test
      - name: Run Integration Tests
        run: |
          bundle exec rake clean integration-test
      - name: Build Package
        run: |
          bundle exec rake install_gem
          bundle exec pmdtester -h
