name: Build Snapshot

on:
  push:
    branches:
      - '**'
      # don't run on dependabot branches. Dependabot will create pull requests, which will then be run instead
      - '!dependabot/**'
  workflow_dispatch:
  schedule:
    # build it monthly: At 04:30 on day-of-month 1.
    - cron:  '30 4 1 * *'

jobs:
  build:
    name: Build Snapshot
    uses: ./.github/workflows/build.yml
