name: manual-integration-tests

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.cache
          vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('pmdtester.gemspec') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup Environment
      shell: bash
      run: |
        echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
        echo "MAVEN_OPTS=-Dmaven.wagon.httpconnectionManager.ttlSeconds=180 -Dmaven.wagon.http.retryHandler.count=3" >> $GITHUB_ENV
        echo "PMD_CI_SCRIPTS_URL=https://raw.githubusercontent.com/pmd/build-tools/master/scripts" >> $GITHUB_ENV
    - name: Check Environment
      shell: bash
      run: |
        f=check-environment.sh; \
        mkdir -p .ci && \
        ( [ -e .ci/$f ] || curl -sSL "${PMD_CI_SCRIPTS_URL}/$f" > ".ci/$f" ) && \
        chmod 755 .ci/$f && \
        .ci/$f
    - name: Build
      run: .ci/manual-integration-tests.sh
      shell: bash
      env:
        PMD_CI_SECRET_PASSPHRASE: ${{ secrets.PMD_CI_SECRET_PASSPHRASE }}
